var indice = {
    Miranda: [
        "index.html",
        "historia.html",
        "parafarmacia.html",
        "contacto.html",
    ],
    alt: ["index.html", "historia.html", "parafarmacia.html", "contacto.html"],
    Farmacia: [
        "index.html",
        "historia.html",
        "parafarmacia.html",
        "contacto.html",
    ],
    texto: ["index.html"],
    buscar: ["index.html"],
    value: ["index.html", "contacto.html"],
    title: ["index.html"],
    onclick: ["index.html"],
    Equipo: ["index.html"],
    completo: ["index.html"],
    negocio: ["index.html", "historia.html"],
    familiar: ["index.html", "historia.html"],
    que: ["index.html", "parafarmacia.html"],
    llevamos: ["index.html"],
    abiertos: ["index.html"],
    publico: ["index.html"],
    siendo: ["index.html"],
    siempre: ["index.html"],
    nuestra: ["index.html", "parafarmacia.html"],
    satisfación: ["index.html"],
    del: ["index.html", "historia.html"],
    cliente: ["index.html"],
    Estamos: ["index.html"],
    servicio: ["index.html", "parafarmacia.html"],
    pra: ["index.html"],
    llevarle: ["index.html"],
    mejor: ["index.html", "parafarmacia.html"],
    atención: ["index.html"],
    farmaceútica: ["index.html"],
    Ingeniería: [
        "index.html",
        "historia.html",
        "parafarmacia.html",
        "contacto.html",
    ],
    Web: ["index.html", "historia.html", "parafarmacia.html", "contacto.html"],
    Oviedo: ["index.html", "historia.html", "parafarmacia.html", "contacto.html"],
    HTML5: ["index.html", "historia.html", "parafarmacia.html", "contacto.html"],
    height: ["index.html", "historia.html", "parafarmacia.html", "contacto.html"],
    width: ["index.html", "historia.html", "parafarmacia.html", "contacto.html"],
    http: ["index.html", "historia.html", "parafarmacia.html", "contacto.html"],
    Triple: ["index.html", "historia.html", "parafarmacia.html", "contacto.html"],
    conformance: [
        "index.html",
        "historia.html",
        "parafarmacia.html",
        "contacto.html",
    ],
    WAI: ["index.html", "historia.html", "parafarmacia.html", "contacto.html"],
    Content: [
        "index.html",
        "historia.html",
        "parafarmacia.html",
        "contacto.html",
    ],
    Accessibility: [
        "index.html",
        "historia.html",
        "parafarmacia.html",
        "contacto.html",
    ],
    Guidelines: [
        "index.html",
        "historia.html",
        "parafarmacia.html",
        "contacto.html",
    ],
    farmacia: ["historia.html"],
    Somos: ["historia.html"],
    des: ["historia.html"],
    hace: ["historia.html"],
    mas: ["historia.html"],
    fue: ["historia.html"],
    fundada: ["historia.html"],
    por: ["historia.html"],
    Manuel: ["historia.html"],
    Gonzalez: ["historia.html"],
    mostrador: ["historia.html"],
    Fundador: ["historia.html"],
    licencio: ["historia.html"],
    principios: ["historia.html"],
    siglo: ["historia.html"],
    fundó: ["historia.html"],
    continuadores: ["historia.html"],
    Ramón: ["historia.html"],
    Sobrino: ["historia.html"],
    Llorca: ["historia.html"],
    Pilar: ["historia.html"],
    Lopez: ["historia.html"],
    licenciaron: ["historia.html"],
    continuaron: ["historia.html"],
    con: ["historia.html", "parafarmacia.html"],
    nueva: ["historia.html"],
    generación: ["historia.html"],
    Leticia: ["historia.html"],
    licención: ["historia.html"],
    continua: ["historia.html"],
    seguir: ["historia.html"],
    haciendo: ["historia.html"],
    muchos: ["historia.html"],
    piel: ["parafarmacia.html"],
    Dermocosmética: ["parafarmacia.html"],
    pasión: ["parafarmacia.html"],
    tenemos: ["parafarmacia.html"],
    amplio: ["parafarmacia.html"],
    surtido: ["parafarmacia.html"],
    productos: ["parafarmacia.html"],
    desde: ["parafarmacia.html"],
    las: ["parafarmacia.html"],
    marcas: ["parafarmacia.html"],
    dermatológicas: ["parafarmacia.html"],
    Endocare: ["parafarmacia.html"],
    Roche: ["parafarmacia.html"],
    Avene: ["parafarmacia.html"],
    para: ["parafarmacia.html"],
    cubrir: ["parafarmacia.html"],
    los: ["parafarmacia.html"],
    problemas: ["parafarmacia.html"],
    salud: ["parafarmacia.html"],
    tratar: ["parafarmacia.html"],
    forma: ["parafarmacia.html"],
    científica: ["parafarmacia.html"],
    eficaz: ["parafarmacia.html"],
    envejecimiento: ["parafarmacia.html"],
    hasta: ["parafarmacia.html"],
    reconocidas: ["parafarmacia.html"],
    cosméticas: ["parafarmacia.html"],
    Eucerin: ["parafarmacia.html"],
    naturales: ["parafarmacia.html"],
    Tambien: ["parafarmacia.html"],
    ofrecemos: ["parafarmacia.html"],
    como: ["parafarmacia.html"],
    foto: ["parafarmacia.html"],
    curso: ["parafarmacia.html"],
    aprender: ["parafarmacia.html"],
    cuidado: ["parafarmacia.html"],
    posible: ["parafarmacia.html"],
    nutricion: ["parafarmacia.html"],
    nuestro: ["parafarmacia.html"],
    dietética: ["parafarmacia.html"],
    encontrarás: ["parafarmacia.html"],
    obtener: ["parafarmacia.html"],
    peso: ["parafarmacia.html"],
    ideal: ["parafarmacia.html"],
    prevenir: ["parafarmacia.html"],
    obesidad: ["parafarmacia.html"],
    Los: ["parafarmacia.html"],
    profesionales: ["parafarmacia.html"],
    encargan: ["parafarmacia.html"],
    estudiar: ["parafarmacia.html"],
    valorar: ["parafarmacia.html"],
    alimenticio: ["parafarmacia.html"],
    adaptan: ["parafarmacia.html"],
    cada: ["parafarmacia.html"],
    persona: ["parafarmacia.html"],
    estudiando: ["parafarmacia.html"],
    variables: ["parafarmacia.html"],
    edad: ["parafarmacia.html"],
    trabajo: ["parafarmacia.html"],
    estado: ["parafarmacia.html"],
    uno: ["parafarmacia.html"],
    esta: ["parafarmacia.html"],
    manera: ["parafarmacia.html"],
    dietista: ["parafarmacia.html"],
    realiza: ["parafarmacia.html"],
    plan: ["parafarmacia.html"],
    nutricional: ["parafarmacia.html"],
    personalizado: ["parafarmacia.html"],
    exhaustivo: ["parafarmacia.html"],
    donde: ["parafarmacia.html"],
    recomendará: ["parafarmacia.html"],
    una: ["parafarmacia.html"],
    dieta: ["parafarmacia.html"],
    específica: ["parafarmacia.html"],
    ajustada: ["parafarmacia.html"],
    sus: ["parafarmacia.html"],
    necesidades: ["parafarmacia.html"],
    objetivo: ["parafarmacia.html"],
    perder: ["parafarmacia.html"],
    bajar: ["parafarmacia.html"],
    colesterol: ["parafarmacia.html"],
    simplemente: ["parafarmacia.html"],
    tener: ["parafarmacia.html"],
    buena: ["parafarmacia.html"],
    alimentación: ["parafarmacia.html"],
    siguiendo: ["parafarmacia.html"],
    unas: ["parafarmacia.html"],
    pautas: ["parafarmacia.html"],
    dudes: ["parafarmacia.html"],
    solicitar: ["parafarmacia.html"],
    visita: ["parafarmacia.html"],
    empezar: ["parafarmacia.html"],
    cuidarte: ["parafarmacia.html"],
    Pedregal: ["contacto.html"],
    Grado: ["contacto.html"],
    Asturias: ["contacto.html"],
    contacto: ["contacto.html"],
    action: ["contacto.html"],
    method: ["contacto.html"],
    enctype: ["contacto.html"],
    nombre: ["contacto.html"],
    name: ["contacto.html"],
    size: ["contacto.html"],
    email: ["contacto.html"],
    mensaje: ["contacto.html"],
    rows: ["contacto.html"],
    cols: ["contacto.html"],
};